import os
from seleniumbase import BaseCase
from seleniumbase.config import settings


class ReportGenerator(BaseCase):
    def generate_report(self):
        # Set the path to the HTML report generated by pytest
        pytest_report_path = "path/to/pytest_report.html"  # Replace with the actual path

        # Set the path to the SeleniumBase dashboard report
        seleniumbase_report_path = os.path.join(settings.DOWNLOADS_FOLDER, "dashboard_report.html")

        # Read the contents of the HTML report generated by pytest
        with open(pytest_report_path, 'r') as f:
            pytest_report_contents = f.read()

        # Read the contents of the SeleniumBase dashboard report
        with open(seleniumbase_report_path, 'r') as f:
            seleniumbase_report_contents = f.read()

        # Combine the contents of both reports
        combined_report_contents = pytest_report_contents + seleniumbase_report_contents

        # Write the combined report to a new file
        combined_report_path = "path/to/combined_report.html"  # Replace with the desired path
        with open(combined_report_path, 'w') as f:
            f.write(combined_report_contents)


if __name__ == '__main__':
    ReportGenerator().generate_report()
